# Base configs
baseurl: "https://emilysgarden.regislaxdad.com"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Emily's Garden"
subtitle: "It keeps us busy on weekends!"
author: "H."
header:
 title: "Emily's Garden"
 subtitle: "by H."
footer:
 name: "Hey there, my name is H."
 bio: "I love photography. And I also love gardening with Emily!"
 github: "Do you Want a website like this for yourself for free? Just <a href=\"https://github.com/regislaxdad/emilysgarden\">fork me on github</a> ;)"
web_design: "AJ"
social_urls:
  facebook: "https://www.facebook.com/f-trump"
  twitter: "https://www.twitter.com/f-trump"
  instagram: "https://www.instagram.com/f-trump"
  dribbble: "https://dribbble.com/f-trump"
  linkedin: "https://in.linkedin.com/in/f-trump"
  github: "https://www.github.com/regislaxdad"
